### ISSUE TITLE
Unable to build oatpp-curl

### ISSUE THREAD

**Issue by puneetugru** [oatpp/oatpp-curl#3]
Hi,

I'm trying to build oatpp-curl on my Ubuntu, for a small project.

I'm able to compile and build oatpp successfully.

But, while trying to build oatpp-curl, I'm getting below error,

cmake CMakeLists.txt -OATPP_DIR_SRC=/home/puugru/Downloads/TestApp/oatpp-master/src/
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Finding oatpp in location=INSTALLED
CMake Error at CMakeLists.txt:41 (find_package):
  By not providing "Findoatpp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "oatpp", but
  CMake did not find one.

  Could not find a package configuration file provided by "oatpp" (requested
  version 0.19.7) with any of the following names:

    oatppConfig.cmake
    oatpp-config.cmake

  Add the installation prefix of "oatpp" to CMAKE_PREFIX_PATH or set
  "oatpp_DIR" to a directory containing one of the above files.  If "oatpp"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/puugru/Downloads/TestApp/oatpp-curl-master/CMakeFiles/CMakeOutput.log".

I'm trying to build oatpp-curl from path /home/puugru/Downloads/TestApp/oatpp-curl-master/
and my TestApp directory looks as below,

puugru@ubuntu:~/Downloads/TestApp$ ls
oatpp-curl-master  oatpp-master

**Comment by lganzzzo** [comment]
Hello @puneetugru ,

Seems like `oatpp-curl` module can't find main `oatpp` module.
Please make sure:
- You have versions of `oatpp` and `oatpp-curl` both `0.19.7`
- You have installed oatpp (not just build):
   ```bash
   # From oatpp/build forlder
   cmake ..
   make install
   ```

Please let me know if it helped.

Regards,
Leonid

**Comment by puneetugru** [comment]
Hi Leonid,

Thanks a lot, that worked.
